### ISSUE TITLE
Explodes on use

### ISSUE THREAD

**Issue by kigster** [evantahler/smartdc-cost#6]
```
❯ sdc-listmachines-cost
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/smartdc-cost/lib/common.js:17:17)
    at Request.self.callback (/usr/local/lib/node_modules/smartdc-cost/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/smartdc-cost/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/smartdc-cost/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
```

Thanks Evan!

**Comment by evantahler** [comment]
Heh, looks like some time in the past 3 years that endpoint got removed, and the data is not just baked into the [page](https://www.joyent.com/pricing/cloud/compute).  It's probably safe to say that this package is EOL.

😢  🎺

**Comment by kigster** [comment]
Well I'm updating my kigster/Joyent-cloud-pricing gem with the latest and tests are green (see PR). 

Wanna collaborate on the gem?

**Comment by evantahler** [comment]
Thanks for the offer, but I haven't use Joyent (or Ruby) for a few years now.  Good luck!
